<?php
$CONF_DB_NAME='zadanie_10';
$CONF_DB_HOST='localhost';
$CONF_DB_USER='xvrabec';
//$CONF_DB_USER='phpmyadmin';
$CONF_DB_PASS='123';
$CONF_SERVER_ADDRESS="localhost";
//$CONF_SERVER_ADDRESS="http://147.175.98.233";
?>
